### ISSUE TITLE
Publish step not including the Angular front-end 

### ISSUE THREAD

**Issue by syedhaid** [devpro/aspnetcore-angular-sample#7]
Hi! Thanks for creating this sample tutorial. I tried using this for my ASP.NET Angular project, however I ran into issues when I set the publishWebProjects: True for the dotnet publish step. In your example, this flag is set to False, so the output package does not contain Angular files. Was that intended? I couldn't find any code in your yaml files that is building and publishing the Angular part of the project.

**Comment by devpro** [comment]
Hi and thank you for asking!

Azure pipelines are defined in `.azure/pipelines` folder:

- [.azure/pipelines/ci.yml](https://github.com/devpro/aspnetcore-angular-sample/blob/master/.azure/pipelines/ci.yml) for continuous integration (triggered build & test)
- [.azure/pipelines/pkg.yml](https://github.com/devpro/aspnetcore-angular-sample/blob/master/.azure/pipelines/ci.yml) for continuous delivery (triggered publish)

Here is the step to publish an ASP.NET Core web application (including Angular or not):

```yaml
- task: DotNetCoreCLI@2
  displayName: 'Publish the web app'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'dotnet/src/**/*Api.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: false
```

`publishWebProjects` is a misleading argument... This is for me a legacy option that was not well thought but you don't need it!

As long a you do a "normal" publish as in the example, the output will be the one you expect (an artifact that can be used as is in a release pipeline with all dll and angular file)!

For more information, feel free to look at the documentation comments about this badly named field: [.NET Core CLI task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
